services:
  backend:
    build:
      args:
      - NODE_ENV=development
      context: backend
      target: development
    environment:
      - NODE_ENV=development
    ports:
      - 9230:9230
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/vite.config.ts:/code/vite.config.ts
    networks:
      - public
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
